export const STARTER_SNIPPET = `"""Generated by westmarch-generic web config editor."""

subsystems = {
    "exploration": {
        "enabled": False,
        "commands": {
            "enc": False,
            "forage": False,
            "fish": False,
            "mine": False,
            "lumber": False,
            "hunt": False,
            "loot": False
        },
        "config": {
            "enc_biome_source": "auto",
            "distribution_policy": "random",
            "distribution": {
                "combat": 25,
                "quest": 25,
                "gather": 50
            },
            "repeat_exclude_window": 5,
            "monster_images": {
                "hunt": "thumbnail",
                "loot": "thumbnail"
            },
            "show_check_dcs": {
                "hunt": True,
                "loot": True
            }
        }
    },
    "travel": {
        "enabled": False,
        "commands": {
            "travel": False,
            "location": False,
            "time": False,
            "weather": False
        },
        "config": {
            "transport_icons": {
                "walk": "🚶",
                "fly": "🪽",
                "horse": "🐎",
                "boat": "⛵"
            }
        }
    },
    "downtime": {
        "enabled": False,
        "commands": {
            "downtime": False
        }
    },
    "crafting": {
        "enabled": False,
        "commands": {
            "craft": False,
            "brew": False,
            "enchant": False,
            "scribe": False
        },
        "config": {
            "rules_version": None,
            "recipe_mode": "mixed",
            "require_known_spell": True,
            "catalogues": {
                "items": "engine:catalogues/items",
                "potions": "engine:catalogues/potions",
                "spells": "engine:catalogues/spells",
                "magic_items": "engine:catalogues/magic_items",
                "recipes": None
            },
            "checks": {
                "craft": {
                    "mode": "none",
                    "skill": None,
                    "ability": None,
                    "dc": None,
                    "require_success": True
                },
                "brew": {
                    "mode": "none",
                    "skill": "nature",
                    "ability": None,
                    "dc": None,
                    "require_success": True
                },
                "enchant": {
                    "mode": "none",
                    "skill": "arcana",
                    "ability": None,
                    "dc": None,
                    "require_success": True
                },
                "scribe": {
                    "mode": "none",
                    "skill": "arcana",
                    "ability": None,
                    "dc": None,
                    "require_success": True
                }
            },
            "tool_policy": {
                "craft": {
                    "mode": "off",
                    "tools": [],
                    "require_proficiency": True,
                    "require_kit": False
                },
                "brew": {
                    "mode": "off",
                    "tools": [
                        "Herbalism Kit",
                        "Alchemist's Supplies",
                        "Brewer's Supplies"
                    ],
                    "require_proficiency": True,
                    "require_kit": False
                },
                "enchant": {
                    "mode": "off",
                    "tools": [],
                    "require_proficiency": True,
                    "require_kit": False
                },
                "scribe": {
                    "mode": "off",
                    "tools": [
                        "Calligrapher's Supplies"
                    ],
                    "require_proficiency": True,
                    "require_kit": False
                }
            },
            "item_handling": None
        },
        "command_config": {
            "craft": {},
            "brew": {},
            "enchant": {},
            "scribe": {}
        }
    },
    "economy": {
        "enabled": False,
        "commands": {
            "job": False,
            "buy": False,
            "sell": False,
            "wallet": False
        },
        "command_config": {
            "job": {
                "cooldown_seconds": 28800,
                "workdays_cost": 0,
                "payout_bands": [
                    {
                        "max": 0,
                        "roll": "0"
                    },
                    {
                        "max": 5,
                        "roll": "1d4-1"
                    },
                    {
                        "max": 10,
                        "roll": "1d4+1"
                    },
                    {
                        "max": 15,
                        "roll": "1d6+1"
                    },
                    {
                        "max": 20,
                        "roll": "1d8+2"
                    },
                    {
                        "roll": "1d8+3"
                    }
                ]
            }
        }
    },
    "content": {
        "enabled": False,
        "commands": {
            "library": False,
            "read": False
        },
        "config": {
            "library_topic_source": "manual",
            "allowed_topics": [],
            "books": None
        }
    },
    "misc": {
        "enabled": False,
        "commands": {
            "quest": False,
            "recipe": False
        }
    }
}

policies = {
    "auth": {
        "require_character": True
    },
    "time": {
        "mode": "manual"
    },
    "travel": {
        "apply_path_costs": False,
        "consume_rations": False,
        "rations_item": "Rations"
    },
    "downtime": {
        "mode": "off",
        "max_workdays": None,
        "acquisition": "manual"
    },
    "crafting": {
        "require_downtime_before_roll": True,
        "auto_deduct_materials": False,
        "auto_deduct_gold": False,
        "resources": {
            "gold": "manual",
            "materials": "manual",
            "items": "manual",
            "downtime": "check",
            "spell_slot": "manual"
        }
    },
    "economy": {
        "enforce_cooldowns": True,
        "enforce_wallet_caps": False,
        "starting_gold": None
    },
    "inventory": {
        "item_handling": {
            "mode": "manual",
            "default_bag": "Equipment",
            "equipment_bag": "Equipment",
            "crafted_bag": "Equipment",
            "potions_bag": "Potions",
            "scrolls_bag": "Scrolls",
            "magic_items_bag": "Equipment",
            "materials_bag": "Materials"
        },
        "track_encumbrance": False,
        "enforce_encumbrance": False,
        "attunement_limit": None,
        "enforce_attunement": False,
        "magic_items_carry_limit": None,
        "enforce_magic_item_limit": False
    },
    "exploration": {
        "enforce_cooldowns": True,
        "avoid_repeat_encounters": "off"
    },
    "combat": {
        "scale_encounters_to_level": False,
        "roll_monster_hp": True,
        "scale_mode": "party_average",
        "max_cr_delta": None,
        "min_cr": None
    },
    "quest": {
        "self_assign": False,
        "max_active": None
    },
    "content": {
        "enforce_read_cooldowns": False,
        "enforce_library_cooldowns": True
    },
    "languages": {
        "allowed": []
    },
    "display": {
        "footer_behaviour": "balanced",
        "command_thumbnail": "default",
        "helpful_tips": [],
        "credits": None
    },
    "player_setup": {
        "enabled": True,
        "require_character": True,
        "hud": {
            "enabled": True,
            "fields": [
                "coins",
                "wallet",
                "location"
            ]
        },
        "checks": []
    }
}
`;
