name: Test
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Environment to deploy to'
        required: true
        default: 'Development'
jobs:
  sourcemap-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo Environment
        env:
          ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}
        run: echo $ENVIRONMENT
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - name: Test Sourcemaps
        run: npm run test-sourcemaps
        env:
          ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo Environment
        env:
          ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}
        run: echo $ENVIRONMENT
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: '0.9.26'
      - run: uv tool install avrae-ls
      - name: Test
        run: avrae-ls --run-tests src --log-level INFO
        env:
          AVRAE_TOKEN: ${{ secrets.AVRAE_TOKEN }}
